### ISSUE TITLE
Lib cannot be used for Windows Phone Projects

### ISSUE THREAD

**Issue by mkostersitz** [nkranitz/transloadit-csharp-sdk#4]
When trying to import the source to a Windows Phone project several of the classes used are not available on Windows Phone 8.
System.Configuration, System.Web.Script.Serialization

**Comment by nkranitz** [comment]
Dear mkostersitz, thank you for your report. I will fix this issue ASAP, also will inform you about the fixes.

**Comment by mkostersitz** [comment]
Thanks a lot for the quick response. Would allow me to use transloadit for some of my windows phone apps without reinventing the wheel.

Mike

Sent from my Windows Phone

**Comment by mkostersitz** [comment]
Thank you for the quick fix.
