### ISSUE TITLE
c#.net - not getting ASSEMBLY_COMPLETED response

### ISSUE THREAD

**Issue by kalyanpkumar** [nkranitz/transloadit-csharp-sdk#7]
I got a sync response with responseFirst.Data["ok"] = ASSEMBLY_EXECUTING.
But I need async response with responseFirst.Data["ok"] = ASSEMBLY_COMPLETED.
I want to wait till process is completed like "PHP integration". I do not want to use notify_url parameter.
But I did not find that how I can use .Net sdk to get asyc response or wait while assembly is completed.

How can i get that... i dont find anything like setblocking as in android... do we have any way to get this done. Please let me know...

**Comment by Acconut** [comment]
As far as I can tell the C# SDK currently does not offer an option to wait until the assembly is completed.
In order to achieve the same effect you have to poll the assembly status by issuing a simple GET to the assembly's URL (see https://transloadit.com/docs/api-docs/#retrieve-the-status-of-an-as... for documentation about this request).
This is the recommended method which is also used by most of the SDKs.

**Comment by kalyanpkumar** [comment]
Hi Marius…

Thanks for the information…

But after how much time we need to call the this GET…

Like say can we call this method as soon as we get the ASSEMBLY_EXECUTING response or do we need to give some time delay??

Please let me know.

Thanks.

Regards
Kalyankumar Parise
Team Lead - iOS Applications Development
M: +91 7396476329 | T: 040 42000654
e-mail : kalyan.p@bravemount.com
skype  : kalyan.parise

**Comment by Acconut** [comment]
You can't expect an assembly to be finished after a fixed time. Instead you should poll at a fixed interval (about 1s) until the status of the assembly is not `ASSEMBLY_EXECUTING` any more. Please be aware that the assembly may have failed and it will return something different than `ASSEMBLY_COMPLETED`.

**Comment by kalyanpkumar** [comment]
Ok.. Thanks... will give a try and will check...

**Comment by kalyanpkumar** [comment]
Hi Marius..

Thanks for the information…

Will be implementing as you suggested.

Thanks…

Regards
Kalyankumar Parise
Team Lead - iOS Applications Development
M: +91 7396476329 | T: 040 42000654
e-mail : kalyan.p@bravemount.com
skype  : kalyan.parise

**Comment by Acconut** [comment]
Sure, no problem.

**Comment by kalyanpkumar** [comment]
Hi Marius..

We are able to get the response of the Assembly status with the Get Method. Thanks for help...
I am closing this ticket.
